# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Biomedical Visualization
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In BIME 591, we explore visualizations used in biomedicine. The class covers
  theory and practice of data visualization, visualization design, guest speakers,
  and a group project.
baseurl: "/bime591" # the subpath of your site, e.g. /blog
url: "http://ngopal.github.io" # the base hostname & protocol for your site
#twitter_username: nikhilgopal
#github_username:  ngopal

# Build settings
markdown: kramdown
